[package]
version = "0.1.0"
name = "morph-prover"
edition = "2021"
default-run = "revm"

[[bin]]
name = "revm"
path = "src/main.rs"
required-features = ["bin-deps"]
[features]
bin-deps = [
    "anyhow",
    "tokio",
]

# features = ["tokio","anyhow"]


[[bin]]
name = "evm"
path = "src/evm.rs"

[[bin]]
name = "vkey"
path = "src/vkey.rs"

[dependencies]
sp1-sdk = { git = "https://github.com/scroll-tech/sp1.git", branch = "scroll-dev-0830" }

serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
serde = { version = "1.0.207", default-features = false, features = ["derive"] }
clap = { version = "4.0", features = ["derive", "env"] }
tracing = "0.1.40"
hex = "0.4.3"
eth-types = { git = "https://github.com/scroll-tech/zkevm-circuits", features = ["scroll"], branch = "feat/sp1" }
anyhow = { version = "1.0", optional = true }
tokio = { version = "1", default-features = false, optional = true }

# workspace
stateless-block-verifier = { path = "../../crates/stateless-block-verifier" }

[build-dependencies]
sp1-helper = "1.1.0"
