[package]
version = "0.1.0"
name = "morph-prover"
edition = "2021"
default-run = "revm"

[[bin]]
name = "revm"
path = "src/main.rs"



[[bin]]
name = "evm"
path = "src/evm.rs"

[[bin]]
name = "vkey"
path = "src/vkey.rs"

[dependencies]
sp1-sdk = { git = "https://github.com/scroll-tech/sp1.git", branch = "scroll-dev-0830" }

anyhow.workspace = true
serde = { workspace = true }
serde_json = { workspace = true }
hex = { workspace = true }
tokio = { workspace = true }
clap = { workspace = true }

# workspace
# workspace
morph-executor = { workspace = true }
sbv-primitives= { workspace = true }

[build-dependencies]
sp1-helper = "1.1.0"
