FROM sp1-base:latest

RUN rustup toolchain list
RUN cargo prove --version

COPY . /app
WORKDIR /app
RUN cd program && cargo prove build
RUN cd script && cargo run --release -- --execute
RUN cd script && cargo run --release -- --prove