FROM sp1-base:latest

RUN cargo prove --version

COPY . /app
WORKDIR /app
RUN cd bin/client && cargo prove build
RUN cd bin/host && cargo run --features="bin-deps" --release -- --execute
RUN cd bin/host && cargo run --features="bin-deps" --release -- --prove