[package]
version = "0.1.0"
name = "verifier-client"
edition = "2021"

[dependencies]
sp1-zkvm =  { git = "https://github.com/scroll-tech/sp1.git", branch = "scroll-dev-0830" }
anyhow.workspace = true
serde = { workspace = true }
serde_json = { workspace = true }

# workspace
morph-executor = { workspace = true }
sbv-primitives= { workspace = true }
